language: rust
cache: cargo
script:
  - rustup component add clippy 
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace
  - cargo check --verbose
  - cargi fmt --verbose
  - cargo clippy --verbose --workspace -- -D warnings